modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="yupixm_core"
version="0.1.1"
displayName="YupixM Core"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="YupixM"

[[dependencies.yupixm_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




